version: 0.1
phases: 
  install:
    commands:
      - wget https://s3-us-west-1.amazonaws.com/wget-mike/ojdbc7.jar
      - mvn install:install-file -Dfile="/home/ec2-user/ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"
  build:
    commands:
      - echo Welcome to the pipeline
      - mvn clean package
artifacts:
  files: 
    - target/ERS.war