version: 0.1
phases: 
  install:
    commands:
      - mvn install:install-file -Dfile="ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"
  build:
    commands:
      - mvn package
      - echo Welcome to the pipeline
      
artifacts:
  files: 
    - /target/ERS.0.0.1-SNAPSHOT.war